### PR TITLE
Make the documentation more neutral

### PR DESCRIPTION
**Pull request by icemelon**
Per offline discussion with @barryWhiteHat, we think it'd be better to make the documentation more neutral and honor the community. Let me know if you have any questions or concerns. open to discussion

### CODE REVIEW

**Comment by ed255** [comment]
Hi @icemelon !

I understand that the reason for that proposal is to show that the project is being done jointly by AppliedZKP team + scroll-tech + community.  So I understand the need to remove the "AppliedZKP" name.

Nevertheless, the reason why I originally wrote "AppliedZKP's zkEVM" is because the way I understand it, zkEVM is a concept.  So we're building **a** zkEVM.  And other teams are building other zkEVMs (like Polygon Hermez 2.0 zkEVM).

Do we have the right to own the word "zkEVM"?  I think we need a name to distinguish ourselves from other zkEVM projects.  What do you think?

---

After discussing this offline with @barryWhiteHat and saying that maybe we need a name, he suggested "zkEVM Community Edition".  That sounds good to me, and serves the purpose of distinguishing it from other zkEVM projects.  What do you think about this name?

**Comment by icemelon** [comment]
@ed255 "zkEVM Community Edition" sounds good to me! I made some update on the title and let me know what you think.

**Review by ed255 — APPROVED** [review]
LGTM! Thanks for taking care of this change :)

**Review by CPerezz — APPROVED** [review]
LGTM!!!! :partying_face:

**Pull request merged**
